# Generated by Django 4.2.6 on 2023-11-19 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(default='', max_length=50)),
                ('task_description', models.CharField(default='', max_length=500)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('assignees', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
