# Generated by Django 4.2.6 on 2023-11-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_priority_alter_task_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Completed'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('CR', 'Critical'), ('MD', 'Medium'), ('LW', 'Low')], max_length=2),
        ),
    ]
