# Generated by Django 4.2.6 on 2023-11-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_user_email_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
