# Generated by Django 4.2.6 on 2023-11-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task'),
        ('tasks', '0004_alter_user_email_verification_token'),
    ]

    operations = [
    ]
