# Generated by Django 4.2.6 on 2023-11-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_status_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('HI', 'High'), ('MD', 'Medium'), ('LW', 'Low')], default='LW', max_length=2),
        ),
    ]
