# Generated by Django 4.2.6 on 2023-11-24 11:53

import datetime
import django.core.validators
from django.db import migrations, models
import tasks.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_merge_20231124_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.date.today, validators=[tasks.validators.validate_not_past_date]),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.CharField(default='', max_length=500, validators=[django.core.validators.MinLengthValidator(10, message='Description must be a minimum of 10 characters')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.CharField(default='', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='Title must be a minimum of 3 characters')]),
        ),
    ]
