# Generated by Django 4.2.6 on 2023-11-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_status_alter_task_priority'),
        ('tasks', '0005_alter_team_team_description_alter_team_team_name'),
        ('tasks', '0006_alter_task_due_date_alter_task_task_description_and_more'),
    ]

    operations = [
    ]
