# Generated by Django 4.2.6 on 2023-11-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_merge_20231128_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('HI', 'High'), ('MD', 'Medium'), ('LW', 'Low')], default='LW', max_length=2),
        ),
    ]
