# Generated by Django 4.2.6 on 2023-11-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_task_assignees_task_assignees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignees',
        ),
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.CharField(default='', max_length=50),
        ),
    ]
