# Generated by Django 4.2.6 on 2023-12-03 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_admins',
            field=models.ManyToManyField(blank=True, related_name='admin_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
