# Generated by Django 4.2.6 on 2023-12-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_hours_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hours_spent',
            field=models.CharField(default='', max_length=500),
        ),
    ]
