# Generated by Django 4.2.6 on 2023-12-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_priority'),
        ('tasks', '0012_alter_task_hours_spent'),
    ]

    operations = [
    ]
