# Generated by Django 4.2.6 on 2023-12-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_merge_20231127_1221'),
        ('tasks', '0013_merge_20231201_1258'),
    ]

    operations = [
    ]
