# Generated by Django 4.2.6 on 2023-12-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_merge_20231208_1520'),
        ('tasks', '0009_team_team_admins'),
        ('tasks', '0015_task_team_alter_task_status'),
    ]

    operations = [
    ]
