# Generated by Django 4.2.6 on 2023-12-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_merge_20231211_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'Not Completed'), ('IN_PROGREESS', 'In Progress'), ('DONE', 'Completed')], default='TODO', max_length=20),
        ),
    ]
