# Generated by Django 4.2.6 on 2023-12-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration_time',
            field=models.DateTimeField(null=True),
        ),
    ]
