# Generated by Django 4.2.6 on 2023-12-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_remove_task_duration_time_task_jelly_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jelly_points',
            field=models.IntegerField(default=0),
        ),
    ]
