# Generated by Django 4.2.6 on 2023-12-13 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_user_jelly_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='jelly_points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, message='Jelly points must be a minimum of 1'), django.core.validators.MaxValueValidator(50, message='Jelly points cannot exceed 50')]),
        ),
    ]
