# Generated by Django 4.2.6 on 2023-12-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_alter_task_hours_spent'),
        ('tasks', '0023_alter_task_status'),
    ]

    operations = [
    ]
