# Generated by Django 4.2.6 on 2023-12-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_merge_20231211_1321'),
        ('tasks', '0023_alter_task_status'),
    ]

    operations = [
    ]
