# Generated by Django 4.2.6 on 2023-12-14 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_merge_0016_merge_20231211_1321_0023_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jelly_points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Jelly points must be a minimum of 0')]),
        ),
    ]
