# Generated by Django 4.2.6 on 2023-12-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_merge_20231213_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hours_spent',
            field=models.CharField(default='', max_length=500),
        ),
    ]
