# Generated by Django 4.2.6 on 2023-12-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_merge_20231213_1541'),
        ('tasks', '0025_alter_task_hours_spent'),
    ]

    operations = [
    ]
