# Generated by Django 4.2.6 on 2023-12-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_alter_user_jelly_points'),
        ('tasks', '0028_merge_20231214_1447'),
    ]

    operations = [
    ]
